### ISSUE TITLE
Set basic environment for backend

### ISSUE THREAD

**Issue by seo2im** [ReactPiscine/Server#1]
## Description
setting framework & directory structure

## Todo
- [ ] install package for framework
- [ ] set directory structure
- [ ] write db connection component
